Download the files and study the structure. Then create a simple content-based recommendation system. If this data proves to be too big for processing, you can use this data Download this data, which is contains a small sample of user, items, and ratings.

If you use the smaller dataset, note that the recommendation function, as written in class, assumes that user-id corresponds to the row (minus one) in the user-item matrix. For example, if there are 500 users, they would have user-ids 1-500. This is not the case for the book rating data--user-ids vary a lot. As such, passing in "1" to the recommendation function does not actually retrieve recommendations for user with user-id=1. This is okay for this assignment. In other words, feel free to use "user-ids" in the range [1, 500] as arguments for your recommendation function, even if those user-ids are not in the users_small.csv file. If you'd like, it should be fairly straightforward to create a mapping between original user-id and row, but this is not necessary and would require you to modify the example code from class.

Steps to follow: 

- Convert each book title, author, publisher into appropriate representations (dataframe/matrix)
- Create user-book rating matrix
- Normalize the ratings
- Predict the items

Finally, recommend a list of 10 books to a particular user based on their profile. Describe the process you followed for building this recommender system in up to a page. Then provide results (top-10 books) for three different users.

In [92]:
import pandas as pd
import numpy as np

In [ ]:
# Step-1: Extract relevant data about user, movies, and ratings.
users = pd.read_csv('C:/Users/Fortu/Downloads/Aut2024/Info 376/assignment8_small/users_small.csv', sep=',',encoding='latin-1')

In [152]:
users.head(5)

Location   Age
User-ID                                   
254      minneapolis, minnesota, usa  24.0
3363       knoxville, tennessee, usa  29.0
4017     new orleans, louisiana, usa  48.0
6242        calgary, alberta, canada   NaN
6251            wahiawa, hawaii, usa  32.0

In [95]:
users.shape

(500, 3)

In [96]:
books = pd.read_csv('C:/Users/Fortu/Downloads/Aut2024/Info 376/assignment8_small/books_small.csv', sep=',', encoding='latin-1')

In [97]:
books.head(5)

ISBN                                         Book-Title  \
0  1841721522  New Vegetarian: Bold and Beautiful Recipes for...   
1  042518630X                                    Purity in Death   
2  042511774X                                  Breathing Lessons   
3  1853260053    Tess of the D'Urbervilles (Wordsworth Classics)   
4  1558531025  Life's Little Instruction Book (Life's Little ...   

          Book-Author  Year-Of-Publication  \
0  Celia Brooks Brown                 2001   
1           J.D. Robb                 2002   
2          Anne Tyler                 1994   
3        Thomas Hardy                 1997   
4    H. Jackson Brown                 1991   

                             Publisher  
0        Ryland Peters &amp; Small Ltd  
1             Berkley Publishing Group  
2             Berkley Publishing Group  
3  NTC/Contemporary Publishing Company  
4                        Thomas Nelson

In [98]:
books.shape

(1000, 5)

In [99]:
ratings = pd.read_csv('C:/Users/Fortu/Downloads/Aut2024/Info 376/assignment8_small/ratings_small.csv', sep=',')

In [100]:
ratings.head(5)

User-ID        ISBN  Book-Rating
0   277427  002542730X           10
1   277427  006092988X            0
2   277427  006440188X            0
3   277427  014029628X            0
4   277427  014100018X            0

In [101]:
ratings.shape

(16978, 3)

In [102]:
# Construct user-movie rating matrix by doing pivot (it's like a join operation in databases)
u_b = ratings.pivot(index='User-ID', columns='ISBN', values='Book-Rating').fillna(0)

In [103]:
u_b.head(5)

ISBN     000649840X  002026478X  002542730X  006000438X  006000925X  \
User-ID                                                               
254             0.0         0.0         0.0         0.0         0.0   
3363            0.0         0.0         0.0         0.0         0.0   
4017            0.0         0.0         0.0        10.0         0.0   
6242            0.0         0.0         0.0         6.0         0.0   
6251            0.0         0.0         0.0         0.0         0.0   

ISBN     006001203X  006008460X  006015957X  006016848X  006017143X  ...  \
User-ID                                                              ...   
254             0.0         0.0         0.0         0.0         0.0  ...   
3363            0.0         0.0         0.0         0.0         0.0  ...   
4017            0.0         0.0         0.0         0.0         0.0  ...   
6242            0.0         0.0         0.0         0.0         0.0  ...   
6251            0.0         0.0         0.0         0.0         0.0  ...   

ISBN     8483101610  849550152X  8804342838  8806142100  8806143042  \
User-ID                                                               
254             0.0         0.0         0.0         0.0         0.0   
3363            0.0         0.0         0.0         0.0         0.0   
4017            0.0         0.0         0.0         0.0         0.0   
6242            0.0         0.0         0.0         0.0         0.0   
6251            0.0         0.0         0.0         0.0         0.0   

ISBN     880781000X  8807813025  8817106100  8845247414  8885989403  
User-ID                                                              
254             0.0         0.0         0.0         0.0         0.0  
3363            0.0         0.0         0.0         0.0         0.0  
4017            0.0         0.0         0.0         0.0         0.0  
6242            0.0         0.0         0.0         0.0         0.0  
6251            0.0         0.0         0.0         0.0         0.0  

[5 rows x 964 columns]

In [104]:
u_b.shape

(500, 964)

In [105]:
# Step-3: normalize ratings.
data = u_b.values
user_mean = np.mean(data, axis=1)
normalizedRating = data - user_mean.reshape(-1, 1)

In [106]:
normalizedRating

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.03112033, -0.03112033, -0.03112033, ..., -0.03112033,
        -0.03112033, -0.03112033],
       [-0.14522822, -0.14522822, -0.14522822, ..., -0.14522822,
        -0.14522822, -0.14522822],
       ...,
       [-0.05186722, -0.05186722, -0.05186722, ..., -0.05186722,
        -0.05186722, -0.05186722],
       [-0.03838174, -0.03838174,  9.96161826, ..., -0.03838174,
        -0.03838174, -0.03838174],
       [-0.01244813, -0.01244813, -0.01244813, ..., -0.01244813,
        -0.01244813, -0.01244813]])

In [107]:
# Step-4: SVD (matrix factorization)
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(normalizedRating, k=100)

In [108]:
U.shape

(500, 100)

In [109]:
sigma.shape

(100,)

In [110]:
Vt.shape

(100, 964)

In [111]:
sigma

array([ 26.43195204,  26.68504208,  26.74594046,  26.85117423,
        26.99996835,  27.0561371 ,  27.19895426,  27.33607412,
        27.59199551,  27.7089803 ,  27.89938401,  28.0263381 ,
        28.32697977,  28.42236875,  28.53531896,  28.654801  ,
        28.80970331,  28.92024512,  29.02761977,  29.25160491,
        29.46863514,  29.72484796,  29.90955785,  30.04479147,
        30.14579294,  30.33305962,  30.51093501,  30.73324233,
        30.86331269,  31.02187005,  31.24752709,  31.37998539,
        31.46450462,  31.55712966,  31.79066699,  32.17806829,
        32.3050293 ,  32.55163507,  32.72159516,  32.82105312,
        32.9308962 ,  33.18670547,  33.44946591,  33.68172438,
        33.86224072,  33.9396138 ,  34.1140978 ,  34.41220363,
        34.61691381,  34.74153984,  35.09233114,  35.3171815 ,
        35.45731077,  35.61641697,  35.90460137,  36.3093148 ,
        36.62574802,  36.99878055,  37.20192566,  37.48929607,
        37.85786914,  37.96619493,  38.26472801,  38.29

In [112]:
# Step-5: get the diagonal entries of sigma (singular values)
sigma = np.diag(sigma)

In [113]:
sigma

array([[ 26.43195204,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,  26.68504208,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,  26.74594046, ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ...,  83.25928575,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
         84.83702201,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , 122.05769804]])

In [114]:
sigma.shape

(100, 100)

In [115]:
# Step-6: reshape and renormalize ratings using weighted/important components/factors
all_user_ratings = np.dot(np.dot(U,sigma), Vt) + user_mean.reshape(-1,1)

In [116]:
all_user_ratings

array([[-4.15020960e-16, -6.38715961e-16, -7.83784419e-17, ...,
        -2.84218837e-16,  4.68750696e-16,  4.60132069e-17],
       [ 3.94638067e-01,  1.02567291e-01, -1.61408076e-01, ...,
         6.56347940e-02, -3.17873755e-02,  1.13543060e-02],
       [-8.67669831e-02,  6.21203269e-01, -4.41078942e-01, ...,
        -1.41546026e-02,  6.80171126e-03,  4.86485363e-03],
       ...,
       [ 1.49452756e-01, -2.74330296e-02,  3.51373188e-01, ...,
         2.38504573e-02, -9.01244560e-02, -1.00170246e-02],
       [ 7.66655476e-03,  9.21588105e-02,  6.86688901e+00, ...,
         3.09078466e-02,  7.77026440e-02,  6.59656321e-02],
       [-8.52392218e-02,  7.58323659e-02, -1.33296922e-01, ...,
         1.87824537e-02, -8.19790438e-02, -2.71880584e-02]])

In [117]:
# Step-7: construct a dataframe with all these user-movie ratings predictions.
preds = pd.DataFrame(all_user_ratings, columns=u_b.columns)

In [ ]:
preds.head(5)

ISBN    000649840X    002026478X    002542730X    006000438X    006000925X  \
0    -4.150210e-16 -6.387160e-16 -7.837844e-17 -7.513176e-16 -2.380380e-16   
1     3.946381e-01  1.025673e-01 -1.614081e-01 -2.199430e-01 -5.954132e-02   
2    -8.676698e-02  6.212033e-01 -4.410789e-01  8.740804e+00  4.162594e-01   
3    -4.961971e-02 -3.297501e-01  3.528934e-01  4.065511e+00 -1.657962e-02   
4    -6.268908e-01  2.071848e-01  6.170809e-01  2.011453e-01 -8.195056e-02   
..             ...           ...           ...           ...           ...   
495   3.029857e-02 -2.489660e-01 -7.388572e-02 -3.973263e-01  3.202351e-01   
496  -6.120009e-02  2.329013e-04 -2.831157e-02 -5.537408e-02  1.835343e-02   
497   1.494528e-01 -2.743303e-02  3.513732e-01 -6.861142e-01 -5.201962e-02   
498   7.666555e-03  9.215881e-02  6.866889e+00 -1.607331e-02  7.188330e-02   
499  -8.523922e-02  7.583237e-02 -1.332969e-01 -6.168739e-02 -4.910069e-02   

ISBN    006001203X    006008460X    006015957X    006016848X    006017143X  \
0     1.523474e-16 -5.476965e-16  4.601321e-17 -3.613717e-16  5.786978e-16   
1     9.328870e-02 -1.330330e-01  1.135431e-02 -3.145381e-01 -1.357872e-02   
2     1.846466e-01 -2.487635e-01  4.864854e-03  9.175410e-01 -2.655525e-01   
3    -3.849007e-01  2.392250e-01  1.399301e-02 -8.802554e-02  4.973122e-01   
4     3.711519e-03  3.428405e-01  2.126359e-02  6.185020e-01 -3.258211e-01   
..             ...           ...           ...           ...           ...   
495   1.746246e-01  1.074263e-01  5.018372e-03  2.198044e+00  2.522426e-01   
496   7.062503e-02  2.276990e-02  3.805583e-02 -4.332005e-02  5.283161e-03   
497   1.460536e-01 -3.534755e-01 -1.001702e-02  6.225570e-01 -2.762604e-01   
498   1.484760e-01  3.667571e-01  6.596563e-02 -1.003123e-01  6.082239e-03   
499  -1.516259e-01 -1.477271e-01 -2.718806e-02 -1.125885e-01 -2.988569e-02   

ISBN  ...    8483101610    849550152X    8804342838    8806142100  \
0     ...  4.601321e-17  4.601321e-17 -2.016608e-16 -2.842188e-16   
1     ...  1.135431e-02  1.135431e-02  5.206467e-02  6.563479e-02   
2     ...  4.864854e-03  4.864854e-03 -9.399739e-03 -1.415460e-02   
3     ...  1.399301e-02  1.399301e-02  3.520635e-02  4.227746e-02   
4     ...  2.126359e-02  2.126359e-02  3.039314e-02  3.343632e-02   
..    ...           ...           ...           ...           ...   
495   ...  5.018372e-03  5.018372e-03  2.177292e-02  2.735776e-02   
496   ...  3.805583e-02  3.805583e-02  2.315063e-02  1.818223e-02   
497   ... -1.001702e-02 -1.001702e-02  1.538359e-02  2.385046e-02   
498   ...  6.596563e-02  6.596563e-02  3.967229e-02  3.090785e-02   
499   ... -2.718806e-02 -2.718806e-02  7.289826e-03  1.878245e-02   

ISBN    8806143042    880781000X    8807813025    8817106100    8845247414  \
0    -2.429398e-16 -2.429398e-16 -3.254978e-16 -2.842188e-16  4.687507e-16   
1     5.884973e-02  5.884973e-02  7.241985e-02  6.563479e-02 -3.178738e-02   
2    -1.177717e-02 -1.177717e-02 -1.653203e-02 -1.415460e-02  6.801711e-03   
3     3.874191e-02  3.874191e-02  4.581302e-02  4.227746e-02 -1.178189e-01   
4     3.191473e-02  3.191473e-02  3.495791e-02  3.343632e-02  3.821813e-01   
..             ...           ...           ...           ...           ...   
495   2.456534e-02  2.456534e-02  3.015019e-02  2.735776e-02 -8.516729e-02   
496   2.066643e-02  2.066643e-02  1.569803e-02  1.818223e-02  1.739650e-02   
497   1.961702e-02  1.961702e-02  2.808389e-02  2.385046e-02 -9.012446e-02   
498   3.529007e-02  3.529007e-02  2.652562e-02  3.090785e-02  7.770264e-02   
499   1.303614e-02  1.303614e-02  2.452877e-02  1.878245e-02 -8.197904e-02   

ISBN    8885989403  
0     4.601321e-17  
1     1.135431e-02  
2     4.864854e-03  
3     1.399301e-02  
4     2.126359e-02  
..             ...  
495   5.018372e-03  
496   3.805583e-02  
497  -1.001702e-02  
498   6.596563e-02  
499  -2.718806e-02  

[500 rows x 964 columns]

In [119]:
preds.shape

(500, 964)

In [ ]:
preds.to_csv('C:/Users/Fortu/Downloads/Aut2024/Info 376/assignment8_small/predictions.csv', index=False)

In [181]:
# Given a matrix of predictions for book ratings, produce recommendations for a given user
def recommend_books(predictions_df, userId, users_df, books_df, original_ratings_df, num_recs):
  # Get and sort the user's predictions
  user_row_number = userId - 1  # userId starts at 1, not 0
  sorted_user_predictions = predictions_df.iloc[user_row_number].sort_values(ascending=False)

  # Get the user's data and merge in the book information
  user_data = original_ratings_df[original_ratings_df['User-ID'] == users.index[user_row_number]]  # Row with user info
  user_full = (user_data.merge(books_df, how='left', left_on='ISBN', right_on='ISBN')
         .sort_values(['Book-Rating'], ascending=False))
  print('User {0} has already rated {1} books.'.format(userId, user_full.shape[0]))
  print('Recommending highest {0} predicted ratings books not already rated.'.format(num_recs))

  # Recommend the highest predicted rating books that the user hasn't seen yet.
  recommendations = (books_df[~books_df['ISBN'].isin(user_full['ISBN'])]
             .merge(pd.DataFrame(sorted_user_predictions).reset_index(), how='left', left_on='ISBN', right_on='ISBN')
             .rename(columns={user_row_number: 'Predictions'})
             .sort_values('Predictions', ascending=False)
             .iloc[:num_recs, :-1])
  return user_full, recommendations

In [187]:
# What we want to do
already_rated, recommendations = recommend_books(preds, 1, users, books, ratings, 10)

User 1 has already rated 16 books.
Recommending highest 10 predicted ratings books not already rated.


In [188]:
already_rated.head(10)

User-ID        ISBN  Book-Rating  \
0      254  006000438X            0   
1      254  014028009X            0   
2      254  014100018X            0   
3      254  038533348X            0   
4      254  038542017X            0   
5      254  043935806X            0   
6      254  044018293X            0   
7      254  051510521X            0   
8      254  051512317X            0   
9      254  051513287X            0   

                                          Book-Title      Book-Author  \
0                       The Death of Vishnu: A Novel       Manil Suri   
1                              Bridget Jones's Diary   Helen Fielding   
2                                           Chocolat    Joanne Harris   
3                                       Cat's Cradle    Kurt Vonnegut   
4  Like Water for Chocolate : A Novel in Monthly ...   LAURA ESQUIVEL   
5  Harry Potter and the Order of the Phoenix (Boo...    J. K. Rowling   
6                                Suffer the Children        John Saul   
7                                       Bitter Sweet  LaVyrle Spencer   
8                                       Rising Tides     Nora Roberts   
9       Face the Fire (Three Sisters Island Trilogy)     Nora Roberts   

   Year-Of-Publication      Publisher  
0                 2002      Perennial  
1                 1999  Penguin Books  
2                 2000  Penguin Books  
3                 1998          Delta  
4                 1995         Anchor  
5                 2003     Scholastic  
6                 1986           Dell  
7                 1995     Jove Books  
8                 2001     Jove Books  
9                 2002     Jove Books

In [184]:
recommendations.head(10)

ISBN                                         Book-Title  \
679  044098761X             A Wind in the Door (Laurel Leaf Books)   
409  044022103X                                     One True Thing   
382  1558745718  Chicken Soup for the Pet Lover's Soul (Chicken...   
431  080411109X                          The Hundred Secret Senses   
223  1576737330  The Prayer of Jabez: Breaking Through to the B...   
337  034542705X                      The Man Who Listens to Horses   
192  067102423X                                       Bag of Bones   
331  044022392X        The Keys to the Street: A Novel of Suspense   
334  067151699X                            The HIDDEN LIFE OF DOGS   
198  1573225517                                      High Fidelity   

                   Book-Author  Year-Of-Publication              Publisher  
679          Madeleine L'Engle                 1976             Laure Leaf  
409              Anna Quindlen                 1995                   Dell  
382              Jack Canfield                 1998  Health Communications  
431                    Amy Tan                 1996              Ivy Books  
223            Bruce Wilkinson                 2000              Multnomah  
337              Monty Roberts                 1998       Ballantine Books  
192               Stephen King                 1999                 Pocket  
331               Ruth Rendell                 1997                   Dell  
334  Elizabeth Marshall Thomas                 1995                 Pocket  
198                Nick Hornby                 1996        Riverhead Books