In [2]:
import pandas as pd
import numpy as np

In [3]:
# Step-1: Extract relevant data about user, movies, and ratings.
u_cols = ['user_id','age','sex','occupation','zip_code']
users = pd.read_csv('C:/Users/Fortu/Downloads/Aut2024/Info 376/ml-100k/ml-100k/u.user', sep='|',names=u_cols,encoding='latin-1')

In [4]:
users.head(5)

user_id  age sex  occupation zip_code
0        1   24   M  technician    85711
1        2   53   F       other    94043
2        3   23   M      writer    32067
3        4   24   M  technician    43537
4        5   33   F       other    15213

In [5]:
users.shape

(943, 5)

In [6]:
m_cols=['movieid','movie title','release date','video release date', 'IMDB URL',
        'unknown','Action','Adventure','Animation','Children\'s','Comedy','Crime',
        'Documentary','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery',
        'Romance','Sci-Fi','Thriller','War','Western']
movies = pd.read_csv('C:/Users/Fortu/Downloads/Aut2024/Info 376/ml-100k/ml-100k/u.item', sep='|', names=m_cols,encoding='latin-1')

In [7]:
movies.shape

(1682, 24)

In [8]:
movies.head(5)

movieid        movie title release date  video release date  \
0        1   Toy Story (1995)  01-Jan-1995                 NaN   
1        2   GoldenEye (1995)  01-Jan-1995                 NaN   
2        3  Four Rooms (1995)  01-Jan-1995                 NaN   
3        4  Get Shorty (1995)  01-Jan-1995                 NaN   
4        5     Copycat (1995)  01-Jan-1995                 NaN   

                                            IMDB URL  unknown  Action  \
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...        0       0   
1  http://us.imdb.com/M/title-exact?GoldenEye%20(...        0       1   
2  http://us.imdb.com/M/title-exact?Four%20Rooms%...        0       0   
3  http://us.imdb.com/M/title-exact?Get%20Shorty%...        0       1   
4  http://us.imdb.com/M/title-exact?Copycat%20(1995)        0       0   

   Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  \
0          0          1           1  ...        0          0       0        0   
1          1          0           0  ...        0          0       0        0   
2          0          0           0  ...        0          0       0        0   
3          0          0           0  ...        0          0       0        0   
4          0          0           0  ...        0          0       0        0   

   Mystery  Romance  Sci-Fi  Thriller  War  Western  
0        0        0       0         0    0        0  
1        0        0       0         1    0        0  
2        0        0       0         1    0        0  
3        0        0       0         0    0        0  
4        0        0       0         1    0        0  

[5 rows x 24 columns]

In [9]:
r_cols = ['user_id','movie_id','rating','unix_timestamp']
ratings = pd.read_csv('C:/Users/Fortu/Downloads/Aut2024/Info 376/ml-100k/ml-100k/u.data', sep='\t',names=r_cols,encoding='latin-1')

In [10]:
ratings.shape

(100000, 4)

In [11]:
ratings.head(5)

user_id  movie_id  rating  unix_timestamp
0      196       242       3       881250949
1      186       302       3       891717742
2       22       377       1       878887116
3      244        51       2       880606923
4      166       346       1       886397596

In [12]:
# Drop the columns we don't need. axis=1 means the operation should be performed on the columns.
ratings = ratings.drop('unix_timestamp', axis=1)
movies = movies.drop('video release date', axis=1)
movies = movies.drop('IMDB URL', axis=1)

In [13]:
# Step-2: Construct user-movie rating matrix by doing pivot (it's like a join operation in databases)
u_m = ratings.pivot(index='user_id',columns='movie_id',values='rating').fillna(0)

In [14]:
u_m.shape

(943, 1682)

In [15]:
u_m.head(5)

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
1          5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2          4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
5          4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   

movie_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                               
1          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 1682 columns]

In [16]:
# Step-3: normalize ratings.
data = u_m.values
ratings_mean = np.mean(data,axis=1)
normalizedRating = data - ratings_mean.reshape(-1,1)

In [17]:
normalizedRating

array([[ 4.41617122,  2.41617122,  3.41617122, ..., -0.58382878,
        -0.58382878, -0.58382878],
       [ 3.86325803, -0.13674197, -0.13674197, ..., -0.13674197,
        -0.13674197, -0.13674197],
       [-0.08977408, -0.08977408, -0.08977408, ..., -0.08977408,
        -0.08977408, -0.08977408],
       ...,
       [ 4.9470868 , -0.0529132 , -0.0529132 , ..., -0.0529132 ,
        -0.0529132 , -0.0529132 ],
       [-0.20035672, -0.20035672, -0.20035672, ..., -0.20035672,
        -0.20035672, -0.20035672],
       [-0.34066587,  4.65933413, -0.34066587, ..., -0.34066587,
        -0.34066587, -0.34066587]])

In [18]:
# Step-4: SVD (matrix factorization)
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(normalizedRating, k=100)

In [19]:
U.shape

(943, 100)

In [20]:
sigma.shape

(100,)

In [21]:
Vt.shape

(100, 1682)

In [22]:
sigma

array([ 48.84092259,  49.04791238,  49.18402717,  49.33425001,
        49.45199564,  49.47701172,  49.74734984,  50.00126427,
        50.2413382 ,  50.37889584,  50.49593207,  50.57155951,
        50.94399906,  50.98574244,  51.09056744,  51.21969382,
        51.5096481 ,  51.61576544,  51.88310956,  51.90040737,
        52.06985382,  52.25368974,  52.46272432,  53.0286032 ,
        53.14037992,  53.2851761 ,  53.42589889,  53.66123738,
        54.00111427,  54.28554726,  54.36296432,  54.56685   ,
        54.85187674,  55.07947868,  55.25092547,  55.36638772,
        55.48796073,  55.64821177,  55.84263234,  56.1786217 ,
        56.23749297,  56.68297093,  56.95428404,  57.250598  ,
        57.3183941 ,  57.40164725,  58.07994869,  58.26306154,
        58.52890725,  58.79414542,  59.07162971,  59.40537828,
        59.48739171,  59.76630567,  60.30759224,  60.56707641,
        61.01360173,  61.33084606,  61.74161844,  62.01002551,
        62.17459904,  62.58726087,  62.81131409,  63.51

In [23]:
# Step-5: get the diagonal entries of sigma (singular values)
sigma = np.diag(sigma)

In [24]:
sigma

array([[ 48.84092259,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,  49.04791238,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,  49.18402717, ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ..., 217.3553494 ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
        244.38398351,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , 522.23169772]])

In [25]:
sigma.shape

(100, 100)

In [26]:
# Step-6: reshape and renormalize ratings using weighted/important components/factors
all_user_ratings = np.dot(np.dot(U,sigma), Vt) + ratings_mean.reshape(-1,1)

In [27]:
all_user_ratings

array([[ 5.21903748,  3.21626391,  2.33004833, ...,  0.00922938,
         0.03466201,  0.17659643],
       [ 2.54617342, -0.18992421,  0.3986522 , ..., -0.00871811,
         0.00685227, -0.02881288],
       [-0.1450416 , -0.10173631, -0.41172225, ...,  0.0067354 ,
        -0.03610967, -0.05811918],
       ...,
       [ 3.80556933, -0.09859273,  0.51377819, ...,  0.0141038 ,
         0.02382768,  0.02100336],
       [ 0.60443361,  0.26492728,  0.23841876, ..., -0.00663687,
         0.02488024, -0.00896763],
       [ 0.86179511,  3.38748431,  2.35758533, ..., -0.02465003,
         0.01382539,  0.01094731]])

In [28]:
# Step-7: construct a dataframe with all these user-movie ratings predictions.
preds = pd.DataFrame(all_user_ratings, columns=u_m.columns)

In [29]:
preds.head(5)

movie_id      1         2         3         4         5         6     \
0         5.219037  3.216264  2.330048  4.070080  2.174042  2.371151   
1         2.546173 -0.189924  0.398652  0.136218  0.219939  0.390755   
2        -0.145042 -0.101736 -0.411722 -0.288039  0.016932 -0.026025   
3         0.258836 -0.191892 -0.029108  0.068951  0.140218  0.109049   
4         4.200703  1.782011  0.068438  0.170432  0.266356  0.114757   

movie_id      7         8         9         10    ...      1673      1674  \
0         4.937889  2.451562  5.018531  2.214036  ...  0.019273 -0.003311   
1         0.373605 -0.107817  1.347373  1.063680  ...  0.027430  0.013848   
2        -0.318215  0.120447 -0.243985  0.198292  ... -0.034298 -0.053417   
3         0.222686 -0.359241  0.014793 -0.092021  ...  0.001857  0.016633   
4         1.386346 -0.020448 -0.302272  0.669130  ...  0.054404 -0.051297   

movie_id      1675      1676      1677      1678      1679      1680  \
0        -0.055446 -0.036462  0.027922  0.005369  0.013090  0.009229   
1        -0.032258 -0.026604 -0.027045 -0.012007 -0.005429 -0.008718   
2         0.022753  0.004712 -0.030537 -0.012318  0.025788  0.006735   
3         0.016123  0.010074  0.006319  0.008731  0.030237  0.019484   
4        -0.025636 -0.018048 -0.065828 -0.010397 -0.025445 -0.017921   

movie_id      1681      1682  
0         0.034662  0.176596  
1         0.006852 -0.028813  
2        -0.036110 -0.058119  
3        -0.004342 -0.033769  
4        -0.012638 -0.071162  

[5 rows x 1682 columns]

In [30]:
preds.shape

(943, 1682)

In [31]:
# Given a matrix of predictions for movie ratings, produce recommendations for a given user
def recommend_movies(predictions_df,userId,movies_df,original_ratings_df,num_recs):
  # Get and sort the user's predictions
  user_row_number = userId - 1 # userId starts at 1, not 0
  sorted_user_predictions = predictions_df.iloc[user_row_number].sort_values(ascending=False)

  # Get the user's data and merge in the movie information
  user_data = original_ratings_df[original_ratings_df['user_id']==(userId)] # Row with user info
  user_full = (user_data.merge(movies_df, how='left',left_on='movie_id', right_on='movieid').sort_values(['rating'],ascending=False))
  print('User {0} has already rated {1} movies.'.format(userId,user_full.shape[0]))
  print('Recommending highest {0} predicted ratings movies not already rated.'.format(num_recs))

  # Recommend the highest predicted rating movies that the user hasn't seen yet.
  recommendations = (movies_df[~movies_df['movieid'].isin(user_full['movie_id'])]).merge(pd.DataFrame(sorted_user_predictions)
                                .reset_index(), how='left',left_on='movieid',right_on='movie_id').rename(
                                  columns={user_row_number:'Predictions'}).sort_values('Predictions',ascending=False).iloc[:num_recs,:-1]
  return user_full, recommendations

In [32]:
# What we want to do
already_rated, recommendations = recommend_movies(preds,1,movies,ratings,10)

User 1 has already rated 272 movies.
Recommending highest 10 predicted ratings movies not already rated.


In [33]:
already_rated.head(10)

user_id  movie_id  rating  movieid  \
254        1       204       5      204   
250        1       216       5      216   
244        1       198       5      198   
32         1        60       5       60   
245        1       124       5      124   
28         1       221       5      221   
242        1       165       5      165   
17         1        64       5       64   
22         1       114       5      114   
19         1       228       5      228   

                                           movie title release date  unknown  \
254                          Back to the Future (1985)  01-Jan-1985        0   
250                     When Harry Met Sally... (1989)  01-Jan-1989        0   
244                    Nikita (La Femme Nikita) (1990)  01-Jan-1990        0   
32                           Three Colors: Blue (1993)  01-Jan-1993        0   
245                                   Lone Star (1996)  21-Jun-1996        0   
28                           Breaking the Waves (1996)  15-Nov-1996        0   
242                            Jean de Florette (1986)  01-Jan-1986        0   
17                    Shawshank Redemption, The (1994)  01-Jan-1994        0   
22   Wallace & Gromit: The Best of Aardman Animatio...  05-Apr-1996        0   
19                 Star Trek: The Wrath of Khan (1982)  01-Jan-1982        0   

     Action  Adventure  Animation  ...  Fantasy  Film-Noir  Horror  Musical  \
254       0          0          0  ...        0          0       0        0   
250       0          0          0  ...        0          0       0        0   
244       0          0          0  ...        0          0       0        0   
32        0          0          0  ...        0          0       0        0   
245       0          0          0  ...        0          0       0        0   
28        0          0          0  ...        0          0       0        0   
242       0          0          0  ...        0          0       0        0   
17        0          0          0  ...        0          0       0        0   
22        0          0          1  ...        0          0       0        0   
19        1          1          0  ...        0          0       0        0   

     Mystery  Romance  Sci-Fi  Thriller  War  Western  
254        0        0       1         0    0        0  
250        0        1       0         0    0        0  
244        0        0       0         1    0        0  
32         0        0       0         0    0        0  
245        1        0       0         0    0        0  
28         0        0       0         0    0        0  
242        0        0       0         0    0        0  
17         0        0       0         0    0        0  
22         0        0       0         0    0        0  
19         0        0       1         0    0        0  

[10 rows x 25 columns]

In [34]:
recommendations.head(10)

movieid                                        movie title release date  \
170      443                                  Birds, The (1963)  01-Jan-1963   
188      461                                       Smoke (1995)  01-Jan-1995   
646      919                  City of Lost Children, The (1995)  01-Jan-1995   
182      455                  Jackie Chan's First Strike (1996)  10-Jan-1997   
201      474  Dr. Strangelove or: How I Learned to Stop Worr...  01-Jan-1963   
31       304                               Fly Away Home (1996)  13-Sep-1996   
150      423                  E.T. the Extra-Terrestrial (1982)  01-Jan-1982   
108      381                            Muriel's Wedding (1994)  01-Jan-1994   
109      382  Adventures of Priscilla, Queen of the Desert, ...  01-Jan-1994   
869     1142                          When We Were Kings (1996)  14-Feb-1997   

     unknown  Action  Adventure  Animation  Children's  Comedy  Crime  ...  \
170        0       0          0          0           0       0      0  ...   
188        0       0          0          0           0       0      0  ...   
646        0       0          1          0           0       0      0  ...   
182        0       1          0          0           0       0      0  ...   
201        0       0          0          0           0       0      0  ...   
31         0       0          1          0           1       0      0  ...   
150        0       0          0          0           1       0      0  ...   
108        0       0          0          0           0       1      0  ...   
109        0       0          0          0           0       1      0  ...   
869        0       0          0          0           0       0      0  ...   

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
170          0       1        0        0        0       0         0    0   
188          0       0        0        0        0       0         0    0   
646          0       0        0        0        0       1         0    0   
182          0       0        0        0        0       0         0    0   
201          0       0        0        0        0       1         0    1   
31           0       0        0        0        0       0         0    0   
150          0       0        0        0        0       1         0    0   
108          0       0        0        0        1       0         0    0   
109          0       0        0        0        0       0         0    0   
869          0       0        0        0        0       0         0    0   

     Western  movie_id  
170        0       443  
188        0       461  
646        0       919  
182        0       455  
201        0       474  
31         0       304  
150        0       423  
108        0       381  
109        0       382  
869        0      1142  

[10 rows x 23 columns]